### ISSUE TITLE
[Feature requests] Read also *.meta files and publish as Kodi Info Addon

### ISSUE THREAD

**Issue by ovz93br43v7** [WolfgangFahl/eitparser#4]
Probably it is possible that also the information from *.meta are used?

Great would be when you could publish your software as an addon for [Kodi](https://kodi.tv/) to provide information about the recorded DVB shows. Currently such a feature / addon don't exist.

**Comment by WolfgangFahl** [comment]
@ovz93br43v7  where would i found such *.meta data files? Could you please supply an example file and the expected output?

**Comment by ovz93br43v7** [comment]
@WolfgangFahl Sure. My enigma2 receiver creates six files per recording. 

- *.eit
- *.ts
- *.ts.ap
- *.ts.cuts
- *.ts.meta
- *.ts.sc

But with gedit I only see useful infos in *.eit and *.ts.meta

Here example files:

**Comment by WolfgangFahl** [comment]
I do have the .meta files on my Vu+ Duo too. I never looked into them. The format seems to be plain text. What information would you like to extract from such a file?
```
cat 20200410\ 2225\ -\ arte\ HD\ -\ Jesus\ Christ\ Superstar\ -\ Live\ in\ Concert.ts.meta 
1:0:19:283E:3FB:1:C00000:0:0:0:
Jesus Christ Superstar - Live in Concert
Musical USA 2019
1586550300

701895600
13607518208
f:0,c:0013f7,c:0213fa,c:0313f7,c:0413fc,c:050001
0
```

**Comment by WolfgangFahl** [comment]
The https://github.com/xbmc/xbmc (Kodi) integration is a different story all together.

**Comment by ovz93br43v7** [comment]
> ```
> 13607518208
> ```
In my case this is the video length, the other numbers I'm not sure. I just thought you overlooked the meta file where probably also useful information are stored.

I was looking for an addon to get the same description as EMC shows for DVB recording in Kodi. I saw your comment in the EMC repo and thought probably you are looking for the same thing.

Nevertheless thanks for your fast answer.
